# Generated by Django 5.1 on 2024-08-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('type', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=10000000)),
            ],
        ),
        migrations.DeleteModel(
            name='PageState',
        ),
    ]
