# Generated by Django 5.1 on 2024-08-21 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='home/static/home')),
                ('reference', models.CharField(max_length=10000000)),
            ],
        ),
        migrations.CreateModel(
            name='Meat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='home/static/home')),
            ],
        ),
        migrations.CreateModel(
            name='MeatProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='home/static/home')),
                ('reference', models.CharField(max_length=10000000)),
                ('meat_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.meat')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
