# Generated by Django 5.1 on 2024-08-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_groceryproduct_meat_meatproduct_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='meatproduct',
            name='is_fresh',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groceryproduct',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='meat',
            name='image',
            field=models.ImageField(upload_to='meat/'),
        ),
    ]
