# Generated by Django 5.1 on 2024-08-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_meatproduct_is_fresh_alter_groceryproduct_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('product', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=600)),
            ],
        ),
        migrations.AlterField(
            model_name='groceryproduct',
            name='image',
            field=models.ImageField(upload_to='grocery'),
        ),
        migrations.AlterField(
            model_name='groceryproduct',
            name='reference',
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='meatproduct',
            name='image',
            field=models.ImageField(upload_to='meat_products/'),
        ),
        migrations.AlterField(
            model_name='meatproduct',
            name='reference',
            field=models.CharField(blank=True, max_length=10000000),
        ),
    ]
