# Generated by Django 5.1 on 2024-08-22 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_form_alter_groceryproduct_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 22, 16, 12, 33, 570256)),
        ),
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='form',
            name='msg',
            field=models.TextField(),
        ),
    ]
