# Generated by Django 5.1 on 2024-09-07 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_form_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 7, 16, 5, 37, 141593)),
        ),
        migrations.AlterField(
            model_name='meat',
            name='image',
            field=models.ImageField(blank=True, upload_to='meat/'),
        ),
    ]
