# Generated by Django 5.1 on 2024-09-08 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_form_created_at_alter_meat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 14, 16, 15, 159256)),
        ),
    ]
